#+------------------------------------------------------------+
#|  ███████╗████████╗██████╗  ██╗ ███╗   ██╗ ██████╗ ███████╗ |
#|  ██╔════╝╚══██╔══╝██╔══██╗ ██║ ████╗  ██║██╔════╝ ██╔════╝ |
#|  ███████╗   ██║   ██████╔╝ ██║ ██╔██╗ ██║██║  ███╗███████╗ |
#|  ╚════██║   ██║   ██╔══██╗ ██║ ██║╚██╗██║██║   ██║╚════██║ |
#|  ███████║   ██║   ██║  ██║ ██║ ██║ ╚████║╚██████╔╝███████║ |
#|  ╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═╝ ╚═╝  ╚═══╝ ╚═════╝ ╚══════╝ |
#|                     Strings - Chat Plugin                  |
#|                         by: wiicart                        |
#|                       pedestriamc.com                      |
#+------------------------------------------------------------+

# NOTE: More configuration options are available in:
#   - broadcasts.yml
#   - messages.yml
#   - channels.yml
#   - logs.yml
# Main Configuration Options:

# (!) PREFIX HAS BEEN MOVED TO "messages.yml" (!)

# Chat message formats are found in channels.yml

# Process chat colors in player chat messages?
# (Players with proper permissions can use chat colors
# like &4 in their messages and the plugin will color them)
process-in-chat-colors: true

# Enable the /chatcolor command?
# Disable this if you're using an alternate chat color plugin
# to avoid conflicts with command registration.
enable-chatcolor: true

# Process placeholders in player chat messages?
# (Players with proper permissions can use
#  placeholders in their messages)
process-in-chat-placeholders: true

# Enable direct messages:
# Should the Strings /msg system be enabled?
msg-enabled: true

# Message format for /msg
# This is for outgoing messages
# Valid placeholders:
# {sender_username} - sender username
# {sender_displayname} - sender display name
# {sender_prefix} - sender prefix
# {sender_suffix} - sender suffix
# {recipient_username} - recipient username
# {recipient_displayname} - recipient display name
# {recipient_prefix} - recipient prefix
# {recipient_suffix} - recipient suffix
# {message} - the sender's message
# ** Compatible with PlaceholderAPI placeholders
msg-format-outgoing: "&8(&7me &8» &7{recipient_username}&8) &e{message}"

# Message format for /msg
# This is for receiving messages
# Valid placeholders:
# {sender_username} - sender username
# {sender_displayname} - sender display name
# {sender_prefix} - sender prefix
# {sender_suffix} - sender suffix
# {recipient_username} - recipient username
# {recipient_displayname} - recipient display name
# {recipient_prefix} - recipient prefix
# {recipient_suffix} - recipient suffix
# {message} - the sender's message
# ** Compatible with PlaceholderAPI placeholders
msg-format-receiving: "&8(&7{sender_username} &8» &7me&8) &e{message}"

# Social Spy text formatting:
# Valid placeholders:
# {sender_username} - sender username
# {sender_displayname} - sender display name
# {sender_prefix} - sender prefix
# {sender_suffix} - sender suffix
# {recipient_username} - recipient username
# {recipient_displayname} - recipient display name
# {recipient_prefix} - recipient prefix
# {recipient_suffix} - recipient suffix
# {message} - the sender's message
# Due to social spy having data of two players, PlaceholderAPI is not supported
social-spy-format: "&8[&cSocialSpy&8] &8(&7{sender_username} &8» &7{recipient_username}&8) &7{message}"

# Should join/leave messages be sent?
# This MUST be true to use custom join leave messages.
enable-join-leave-messages: true


# Use custom join and leave messages?
# If enabled, default join and leave messages will be replaced with
# your input in the following two config options.
custom-join-leave-message: false

# Custom join message:
# Placeholder list:
# {displayname}
# {username}
# {prefix}
# {suffix}
# Any PlaceholderAPI placeholders
join-message: "&8[&a+&8] &f{username} &7has joined the server."

# Custom leave message:
# Placeholder list:
# {displayname}
# {username}
# {prefix}
# {suffix}
# Any PlaceholderAPI placeholders
leave-message: "&8[&4-&8] &f{username} &7has left the server."

# Send users a MOTD when they join the server?
enable-motd: false

# The MOTD that is sent out if enable-motd is true.
# Placeholder list:
# {displayname}
# {username}
# {prefix}
# {suffix}
# Any PlaceholderAPI placeholders
motd:
  - "&fWelcome to the server, {username}!"
  - "&fHave fun!"

# Broadcast prefix:
# Prefix for messages sent using the /broadcast command
broadcast-format: "&8[&3Broadcast&8] &f"

# Enable PlaceholderAPI support?
# It is advised to keep this enabled
placeholder-api: true

# Chat Filter Config
# All settings for the chat filter.
# Filter can be bypassed with the permission strings.filter.bypass

# URL Whitelist
# (!) MOVED TO moderation.yml

# Mentioning Options

# Enable mentioning?
enable-mentions: true

# Enable @everyone mentions?
# Players will still need the permission strings.mention.all to use this.
mention-everyone: true

# Mention Chat Format:
# NOT IMPLEMENTED YET, WILL BE IMPLEMENTED NEXT UPDATE.
# MEANWHILE, USE "mention-color"; THIS WILL BE SHOWN TO ALL PLAYERS.
# How should the text change in chat when a player uses @<username>?
# NOTE: This will change it for ALL players.
# The option mention-color represents what it will look like for the mentioned player.
mention-chat-format: "&7"

# Mention Color:
# This represents how mentions will be colored in the chat of the mentioned player.
mention-color: "&e"

# Mention Format:
# This text will show up in the mentioned player's action bar.
# Available Placeholders:
# - %sender% - who mentioned you?
mention-format: "&e%sender% mentioned you."

# Mention Sound:
# The sound that is played to mentioned players.
# Options:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
mention-sound: "BLOCK_NOTE_BLOCK_PLING"

# Mention Pitch:
# Players hear a sound any time they're pinged.
# This modifies the pitch of the sound.  Be cautious with this.
# See the link below for options:
# https://minecraft.wiki/w/Note_Block
mention-pitch: 0.594604

# Mention Volume:
# How loud should the note block sound be for the player?
mention-vol: 10

# Should HelpOP be enabled?
enable-helpop: true

# Are disabling HelpOP because you're using another HelpOP plugin?
# Set this to true if so.
other-helpop: false






