package com.pedestriamc.strings.message;

public enum Message {
    NO_PERMS, CHAT_CLEARED, CHAT_CLEARED_ALL, TOO_MANY_ARGS, COOL_DOWN, UNKNOWN_PLAYER, PLAYER_OFFLINE, NO_REPLY, INSUFFICIENT_ARGS, SELF_MESSAGE, SOCIAL_SPY_ON, SOCIAL_SPY_OFF, CHANNEL_JOINED, CHANNEL_ACTIVE, INVALID_USE_CHANNEL
}
