main: com.pedestriamc.strings.moderation.StringsModeration
name: StringsModeration
version: '1.5'
author: wiicart
description: "Moderation expansion for Strings"
api-version: '1.16'
depend:
  - Strings
loadbefore:
  - Strings