# Strings | Emoji Configuration

# Should emojis in chat messages (like :smile:) be replaced with emoji equivalents?
# Emoji codes match Discords. Modifiable in emojis.json
# (Requires the permission strings.chat.emojis)
replacement: true

# Should the Allure Emoji Pack by P4ncake be set as a server resource pack?
# This resource pack adds custom textures for over 300 emojis.
# https://modrinth.com/resourcepack/allure-emoji-pack
resource-pack: false

# The Modrinth ID of the Emoji resource pack
# https://modrinth.com/resourcepack/allure-emoji-pack
pack-id: "mh6HfOTP"

# The header message before the list of emojis with /emoji
# Uses MiniMessage (https://webui.advntr.dev)
command-header: "<dark_gray>[<yellow>Emoji Menu</yellow>]</dark_gray> <gray>-</gray> <white>Click to copy</white>"

# The footer message after the list of emojis with /emoji
# Uses MiniMessage (https://webui.advntr.dev)
command-footer: "<white>Textures from the</white> <click:open_url:'https://modrinth.com/resourcepack/allure-emoji-pack'><aqua>Allure Emoji Pack</aqua></click>"

# Emojis here will be shown in the /emoji command
# The /emoji command provides a list of emojis that can be clicked on to copy.
# By default, this list shows all the emojis with custom textures from the Allure Emoji Pack.
textured-list:
  - ":hugging:"
  - ":face_with_hand_over_mouth:"
  - ":shushing_face:"
  - ":thinking:"
  - ":cowboy:"
  - ":triumph:"
  - ":rage:"
  - ":angry:"
  - ":face_with_symbols_over_mouth:"
  - ":smiling_imp:"
  - ":imp:"
  - ":skull:"
  - ":skull_crossbones:"
  - ":zipper_mouth:"
  - ":face_with_raised_eyebrow:"
  - ":neutral_face:"
  - ":expressionless:"
  - ":no_mouth:"
  - ":smirk:"
  - ":unamused:"
  - ":rolling_eyes:"
  - ":grimacing:"
  - ":lying_face:"
  - ":relieved:"
  - ":pensive:"
  - ":sleepy:"
  - ":drooling_face:"
  - ":sleeping:"
  - ":grinning:"
  - ":smiley:"
  - ":smile:"
  - ":grin:"
  - ":laughing:"
  - ":sweat_smile:"
  - ":rofl:"
  - ":joy:"
  - ":slight_smile:"
  - ":upside_down:"
  - ":wink:"
  - ":blush:"
  - ":innocent:"
  - ":yum:"
  - ":stuck_out_tongue:"
  - ":stuck_out_tongue_winking_eye:"
  - ":crazy_face:"
  - ":stuck_out_tongue_closed_eyes:"
  - ":money_mouth:"
  - ":mask:"
  - ":thermometer_face:"
  - ":head_bandage:"
  - ":nauseated_face:"
  - ":face_vomiting:"
  - ":sneezing_face:"
  - ":hot_face:"
  - ":cold_face:"
  - ":woozy_face:"
  - ":dizzy_face:"
  - ":exploding_head:"
  - ":checkered_flag:"
  - ":triangular_flag_on_post:"
  - ":crossed_flags:"
  - ":flag_black:"
  - ":flag_white:"
  - ":bread:"
  - ":croissant:"
  - ":french_bread:"
  - ":flatbread:"
  - ":pretzel:"
  - ":bagel:"
  - ":pancakes:"
  - ":waffle:"
  - ":cheese:"
  - ":meat_on_bone:"
  - ":poultry_leg:"
  - ":cut_of_meat:"
  - ":bacon:"
  - ":hamburger:"
  - ":fries:"
  - ":pizza:"
  - ":hotdog:"
  - ":sandwich:"
  - ":taco:"
  - ":burrito:"
  - ":tamale:"
  - ":stuffed_flatbread:"
  - ":falafel:"
  - ":egg:"
  - ":cooking:"
  - ":shallow_pan_of_food:"
  - ":stew:"
  - ":fondue:"
  - ":bowl_with_spoon:"
  - ":green_salad:"
  - ":popcorn:"
  - ":butter:"
  - ":salt:"
  - ":canned_food:"
  - ":red_circle:"
  - ":orange_circle:"
  - ":yellow_circle:"
  - ":green_circle:"
  - ":blue_circle:"
  - ":purple_circle:"
  - ":brown_circle:"
  - ":black_circle:"
  - ":white_circle:"
  - ":red_square:"
  - ":orange_square:"
  - ":yellow_square:"
  - ":green_square:"
  - ":blue_square:"
  - ":purple_square:"
  - ":brown_square:"
  - ":black_large_square:"
  - ":white_large_square:"
  - ":black_medium_square:"
  - ":white_medium_square:"
  - ":black_medium_small_square:"
  - ":white_medium_small_square:"
  - ":black_small_square:"
  - ":white_small_square:"
  - ":large_orange_diamond:"
  - ":large_blue_diamond:"
  - ":small_orange_diamond:"
  - ":small_blue_diamond:"
  - ":small_red_triangle_up:"
  - ":small_red_triangle_down:"
  - ":diamond_shape_with_a_dot_inside:"
  - ":radio_button:"
  - ":white_square_button:"
  - ":black_square_button:"
  - ":red_hair:"
  - ":curly_hair:"
  - ":white_hair:"
  - ":bald:"
  - ":clap:"
  - ":raised_hands:"
  - ":heart_hands:"
  - ":open_hands:"
  - ":palms_up:"
  - ":handshake:"
  - ":pray:"
  - ":thumbsup:"
  - ":thumbsdown:"
  - ":fist:"
  - ":facepunch:"
  - ":left_facing_fist:"
  - ":right_facing_fist:"
  - ":wave:"
  - ":raised_back_of_hand:"
  - ":hand_splayed:"
  - ":raised_hand:"
  - ":vulcan:"
  - ":rightwards_hand:"
  - ":leftwards_hand:"
  - ":palm_down_hand:"
  - ":palm_up_hand:"
  - ":leftwards_pushing_hand:"
  - ":rightwards_pushing_hand:"
  - ":ok_hand:"
  - ":pinched_fingers:"
  - ":pinching_hand:"
  - ":v:"
  - ":fingers_crossed:"
  - ":hand_with_index_finger_and_thumb_crossed:"
  - ":love_you_gesture:"
  - ":metal:"
  - ":call_me:"
  - ":writing_hand:"
  - ":nail_care:"
  - ":selfie:"
  - ":point_left:"
  - ":point_right:"
  - ":point_up_2:"
  - ":middle_finger:"
  - ":point_down:"
  - ":point_up:"
  - ":point:"
  - ":love_letter:"
  - ":cupid:"
  - ":gift_heart:"
  - ":sparkling_heart:"
  - ":heartpulse:"
  - ":heartbeat:"
  - ":revolving_hearts:"
  - ":two_hearts:"
  - ":heart_decoration:"
  - ":heavy_heart_exclamation:"
  - ":broken_heart:"
  - ":heart:"
  - ":pink_heart:"
  - ":orange_heart:"
  - ":yellow_heart:"
  - ":green_heart:"
  - ":blue_heart:"
  - ":light_blue_heart:"
  - ":purple_heart:"
  - ":brown_heart:"
  - ":black_heart:"
  - ":grey_heart:"
  - ":white_heart:"
  - ":heart_on_fire:"
  - ":mending_heart:"
  - ":see_no_evil:"
  - ":hear_no_evil:"
  - ":speak_no_evil:"
  - ":speaking_head:"
  - ":bust_in_silhouette:"
  - ":busts_in_silhouette:"
  - ":people_hugging:"
  - ":family:"
  - ":footprints:"
  - ":bone:"
  - ":bouquet:"
  - ":cherry_blossom:"
  - ":white_flower:"
  - ":lotus:"
  - ":rosette:"
  - ":rose:"
  - ":wilted_rose:"
  - ":hibiscus:"
  - ":sunflower:"
  - ":blossom:"
  - ":tulip:"
  - ":hyacinth:"
  - ":soccer:"
  - ":baseball:"
  - ":softball:"
  - ":basketball:"
  - ":volleyball:"
  - ":football:"
  - ":rugby_football:"
  - ":tennis:"
  - ":flying_disc:"
  - ":bowling:"
  - ":cricket_game:"
  - ":field_hockey:"
  - ":ice_hockey:"
  - ":lacrosse:"
  - ":table_tennis:"
  - ":badminton:"
  - ":boxing_glove:"
  - ":martial_arts_uniform:"
  - ":goal:"
  - ":golf:"
  - ":ice_skate:"
  - ":fishing_pole_and_fish:"
  - ":diving_mask:"
  - ":running_shirt_with_sash:"
  - ":ski:"
  - ":sled:"
  - ":curling_stone:"
  - ":frog:"
  - ":crocodile:"
  - ":turtle:"
  - ":lizard:"
  - ":snake:"
  - ":dragon_face:"
  - ":dragon:"
  - ":sauropod:"
  - ":t-rex:"
  - ":medal:"
  - ":trophy:"
  - ":sports_medal:"
  - ":first_place:"
  - ":second_place:"
  - ":third_place:"
  - ":muscle:"
  - ":mechanical_arm:"
  - ":mechanical_leg:"
  - ":leg:"
  - ":foot:"
  - ":ear:"
  - ":ear_with_hearing_aid:"
  - ":nose:"
  - ":brain:"
  - ":anatomical_heart:"
  - ":lungs:"
  - ":tooth:"
  - ":bone:"
  - ":eyes:"
  - ":eye:"
  - ":tongue:"
  - ":lips:"
  - ":biting_lip:"
  - ":smiley_cat:"
  - ":smile_cat:"
  - ":joy_cat:"
  - ":heart_eyes_cat:"
  - ":smirk_cat:"
  - ":kissing_cat:"
  - ":scream_cat:"
  - ":crying_cat_face:"
  - ":pouting_cat:"
  - ":kiss:"
  - ":100:"
  - ":anger:"
  - ":boom:"
  - ":dizzy:"
  - ":sweat_drops:"
  - ":dash:"
  - ":hole:"
  - ":speech_balloon:"
  - ":left_speech_bubble:"
  - ":anger_right:"
  - ":thought_balloon:"
  - ":zzz:"
  - ":jack_o_lantern:"
  - ":christmas_tree:"
  - ":fireworks:"
  - ":sparkler:"
  - ":firecracker:"
  - ":sparkles:"
  - ":balloon:"
  - ":tada:"
  - ":confetti_ball:"
  - ":tanabata_tree:"
  - ":bamboo:"
  - ":dolls:"
  - ":flags:"
  - ":wind_chime:"
  - ":rice_scene:"
  - ":red_envelope:"
  - ":ribbon:"
  - ":gift:"
  - ":reminder_ribbon:"
  - ":tickets:"
  - ":ticket:"
  - ":smiling_face_with_three_hearts:"
  - ":heart_eyes:"
  - ":star-struck:"
  - ":kissing_heart:"
  - ":kissing:"
  - ":relaxed:"
  - ":kissing_closed_eyes:"
  - ":kissing_smiling_eyes:"
  - ":smiling_face_with_tear:"
  - ":confused:"
  - ":face_exhaling:"
  - ":worried:"
  - ":slightly_frowning:"
  - ":frowning2:"
  - ":open_mouth:"
  - ":hushed:"
  - ":astonished:"
  - ":flushed:"
  - ":pleading_face:"
  - ":face_holding_back_tears:"
  - ":frowning:"
  - ":anguished:"
  - ":fearful:"
  - ":cold_sweat:"
  - ":disappointed_relieved:"
  - ":cry:"
  - ":sob:"
  - ":scream:"
  - ":confounded:"
  - ":persevere:"
  - ":disappointed:"
  - ":sweat:"
  - ":weary:"
  - ":tired_face:"
  - ":yawning_face:"
  - ":poop:"
  - ":clown:"
  - ":japanese_ogre:"
  - ":japanese_goblin:"
  - ":ghost:"
  - ":alien:"
  - ":space_invader:"
  - ":robot:"
  - ":sunglasses:"
  - ":nerd:"
  - ":face_with_monocle:"
