name: Java CI with Maven

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Upload all JAR files from all modules
        uses: actions/upload-artifact@v4
        with:
          name: JAR-Packages
          path: '**/target/*.jar'
